### ISSUE TITLE
Center extension within tab

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#102]
**Issue** I merged #100, which correctly reverted the width to the way it was originally.  But now the extension is all the way to the left of the tab:

Chrome:
![image](https://user-images.githubusercontent.com/225111/97645796-84d22f00-1a13-11eb-9aef-601390f49e91.png)

Firefox:
<img width="1152" alt="Screen Shot 2020-10-29 at 6 22 48 PM" src="https://user-images.githubusercontent.com/225111/97645913-d1b60580-1a13-11eb-8e43-6928f3c18fba.png">

**Desired Behavior** Can you make the extension centered within the tab?  Keep the same width (that's good as is), but have it centered instead of all the way to the left.

**Comment by ionutiorgulescu** [comment]
<img width="1680" alt="Screenshot 2020-11-02 at 09 51 42" src="https://user-images.githubusercontent.com/5168735/97842952-2944c180-1cf1-11eb-9c50-84f34bd2182f.png">
