### ISSUE TITLE
Complete uninstall/reinstall on Firefox causes error

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#110]
**Steps to reproduce**
1. Completely remove the extension from Firefox (`about:debugging` -> `This Firefox` -> click `Remove` for the extension)
2. Re-add the extension with build based on latest tip of master
3.  Enter your wallet+key in the modal and click the ok button.
4.  Observe this error:

```
ERROR: start node failed: Lock already being held for file: filecoinretrieval/repo.lock
```

**Suggested fix**
When the extension is removed, can we also remove this repo.lock?  Alternatively, when the extension is initially installed, can it check for (and remove) any old copy of repo.lock?

**Comment by ionutiorgulescu** [comment]
I tested with this [PR](https://github.com/filecoin-shipyard/browser-retrieval/pull/120) and this issue is no longer present.

**Comment by ghost** [comment]
Mike to retest with PR

**Comment by ghost** [comment]
Closing - can't reproduce
