### ISSUE TITLE
Extension should default to prod when no `.env` file is present

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#116]
The extension should default to prod and work correctly when no `.env` file is present.  In other words, let's make sure the having no `.env` file is equivalent to having this in an `.env` file:

```
# PROD
REACT_APP_PROXY_SERVER="wss://retrievalproxy.browser-retrieval.filecoin.io:443"
# DEV
# REACT_APP_PROXY_SERVER="ws://localhost:3000"
```

**Comment by ionutiorgulescu** [comment]
@brunolm already did this.
