### ISSUE TITLE
Prevent Socket.io from falling back to HTTP

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#122]
It results in this error if Sockets.io try and fails to make a websocket connection and then falls back to HTTP(S)

![Screen Shot 2020-11-05 at 9.24.44 AM.png](https://images.zenhubusercontent.com/570c0b3dbf93871ccd993de3/11317cd3-9179-43f1-9775-5dfd3d8df6fe)

Disable fallback to http(s)

**Comment by brunolm** [comment]
https://socket.io/docs/server-api/

```
transports | ['polling', 'websocket'] | transports to allow connections to
```

**Comment by ghost** [comment]
@brunolm Close once you've double checked.

**Comment by brunolm** [comment]
Yes, it's configured here:
https://github.com/filecoin-shipyard/browser-retrieval/blob/a884fa01ccbd652165440aa411a7bef1ba5c727e/src/shared/socket-client/SocketClient.ts#L107
