### ISSUE TITLE
Create a minimum failing test of ipfs importer/exporter

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#129]
The purpose of this issue is to be able to explain the problem we are having with the importer and exporter to the IPFS team without any of them having to know about the browser extension.  My proposal is like this:

 - Create a new repo
 - Create an index.js that looks something like this:

```
import importer from 'ipfs-unixfs-importer';
import exporter from 'ipfs-unixfs-exporter';
[**other imports as needed**]

// hard code the full bytes of 
// `bafk2bzacebhlhbcnhmvover42qq5bx773c522skieho6nhtbz7d2ow3f4sw24` 
// as base64 (here are the first few)
data_sw24 = 'iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAe1BMVEUAkP////8Ajv8Aif8Ai/8A
iv8Ah/8Akf/s9v/0+v/D3//5/f/c7f/T6P+lz//o9P+z1/8el/+HwP+82//j8f+dy//M5P9frv/b.......';

//
// Push `data_sw24` into an importer sink under the CID 
//`bafk2bzacebhlhbcnhmvover42qq5bx773c522skieho6nhtbz7d2ow3f4sw24`
//
    const entry = await last(
      importer(
        [{ content }],
        {
          put: async (data, { cid }) => {
            const block = new Block(data, cid);
            return this.blockService.put(block);
          },
        },
        options,
      ),
    );

//
// Try to export the bytes previously pushed using the same code we 
// generate for the action on the blue down array
//
```

 - Create a package.json to with this
 - Get it running in any browser.  (It needs to run in a browser because IndexedDB is an integral part of this whole problem.)
 - The above example with `bafk2bzacebhlhbcnhmvover42qq5bx773c522skieho6nhtbz7d2ow3f4sw24` should work, since it works in our browser extension today
 - Now re-run index.js with a change in put that differs only in the CID.  Pick a `dag-pb` CID that we know **does not** work in the browser extension; for example:  `bafykbzaceb7xzlm65omwugcavfxxcxclhnwamjbcodz5rz4kbyhenq7m4pivg`
 - We expect that this should fail.  We predict that the link generated for the blue download arrow will not be able to reconstruct the hard coded bytes from `bafykbzaceb7xzlm65omwugcavfxxcxclhnwamjbcodz5rz4kbyhenq7m4pivg` even though all of the other code is unchanged.

If we can get this far, we have a reproducible example of the problem that doesn't depend on the extension, doesn't depend on the network, etc., and fits entirely in a single index.js file.  We can then ask for help with making that work.

**Comment by aistoc** [comment]
Here's the final app: https://github.com/Digital-MOB-Filecoin/ipfs-cid-checker
