### ISSUE TITLE
Query message repeats itself after some time

### ISSUE THREAD

**Issue by brunolm** [agencyenterprise/filecoin-retrieval-browser-extension#154]
1. query for a CID
1. leave the window open for N minutes
1. notice that the message repeated and you have duplicated offers

**Comment by ionutiorgulescu** [comment]
This issue is no longer reproduce after #153 was merged.

**Comment by brunolm** [comment]
I have not seen this happen again after the merge either. I guess we can close and if we see anything weird we can re-open.
