### ISSUE TITLE
Save voucher to submit later if deal fails

### ISSUE THREAD

**Issue by aistoc** [agencyenterprise/filecoin-retrieval-browser-extension#158]
Right now, every time we receive a voucher, we immediately update the channel with this voucher.  This is slow because we're doing an on-chain interaction for every single voucher.

What we should instead do is save each {voucher, pch} tuple in local storage.  Then at the end of the transfers (whether it's successful or failed half way through), we must pick the highest value voucher in our set of {voucher, pch} tuples and submit only that.  The other tuples in the set should be discarded.

**Comment by ghost** [comment]
This will increase performance a lot.
