### ISSUE TITLE
Set up Github Action to update server on every PR merged into master

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#181]
Every time a PR is merged into **master**, we should trigger the web server to do `git pull && yarn && yarn build`

**Comment by brunolm** [comment]
[Actions · filecoin-shipyard/browser-retrieval](https://github.com/filecoin-shipyard/browser-retrieval/actions)

The deploy configuration is in the repository itself, under `.github/workflows/main.yml`
