### ISSUE TITLE
Runbook for how to set up CORS server on a Lotus node

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#19]
I assume this is just an nginx or similar proxy, but we should document the steps somewhere.

**Comment by gfpacheco** [comment]
I added a wiki page with instructions on how to do it: https://github.com/agencyenterprise/filecoin-retrieval-browser-extension/wiki/Enable-CORS-on-a-Lotus-API

**Comment by ghost** [comment]
LGTM
