### ISSUE TITLE
BUG: Cannot copy and paste configuration options

### ISSUE THREAD

**Issue by chafey** [agencyenterprise/filecoin-retrieval-browser-extension#22]
Observed: It is not possible to configure the extension via copy and paste of parameters because the popup closes when you tab out to another window to copy another configuration parameter and loses in progress changes
Expected: Popup should not close, or remember the in progress configuration changes
Environment: Firefox on PopOS 20.04 (Ubuntu 20.04 based)
Steps to reproduce:
1) Install extension on firefox
2) Copy one of the configuration parameters into the clipboard (e.g. lotus endpoint)
3) Click "Filecoin" icon
4) Click "Options"
5) Paste the configuration parameter in the clipboard into a text box on the configuration screen
6) Tab to another application (e.g. slack) to copy the next configuration parameter (e.g. JWT Wallet)
7) Tab back to browser, observe that popup is no longer visible
8) Click "Filecoin" icon
9) Click "Options", observe that the first configuration item pasted on step 5 is gone

**Comment by ionutiorgulescu** [comment]
Firefox behavior close all popups when extension is losing focus, it's an opened issue 4 years ago and still not resolved, https://bugzilla.mozilla.org/show_bug.cgi?id=1292701  there are two workarounds: 
1. to open the extension as a browser page like this: moz-extension://"ID"/index.html 
    - ID can be found here about:debugging#/runtime/this-firefox and it's the Internal UUID from Filecoin Retreival extension
2. to disable the autohide, but this will make the extension always opened. 
    - this can be done from about:config then search for ui.popup.disable_autohide and make it true

Edit: I've add a new icon near PeersIndicator, if clicked will open the extension as a webpage. (PR: #33)

DEMO: https://drive.google.com/file/d/1uc_Wkvpee-dFwxMIxxkSY4SgyBYi9Mk0/view?usp=sharing
