### ISSUE TITLE
Convert browser extension to web app

### ISSUE THREAD

**Issue by aistoc** [agencyenterprise/filecoin-retrieval-browser-extension#25]
This will include:

- [x] redesign the project structure

- [x] bundle the web app using parcel

- [x] convert the frontend side from extension to web app

- [ ] adapt the communication between frontend and background

- [ ] adapt the background side to be run by the web app

- [x] upgrade libp2p and its dependencies to latest

**Comment by aistoc** [comment]
At this moment the web page is loading and all the visual components are working, but the message exchange mechanism is corrupted. 

To fix this, a total refactoring of the code is needed, including the background and the popup part. 
The entire code should be split in react components.

Tried to find an easy way to make the communication work, but couldn't find any. 
I excluded RabbitMQ and PostMessage Web API, and also had a few fast tries with Redux and React, which made me realise the above conclusions.

**Comment by brunolm** [comment]
I think any message exchanging things would be overkill, there's no need to keep the messaging system. We can just convert into a  full frontend website.

**Comment by aistoc** [comment]
Yes, totally agreed.

**Comment by ghost** [comment]
@brunolm @aistoc Can I close this?

**Comment by aistoc** [comment]
@mgoelzer Sure.
