### ISSUE TITLE
Upload fails in Firefox

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#31]
Uploading a file to the extension fails in Firefox, but works correctly in Chrome.  Maybe be a side effect of #29.

[Here is a video showing how it fails in Firefox.](https://drive.google.com/file/d/1EMF0QwPAbDt-HY_mwgEEHll7sHPQ9uzY/view?usp=sharing)

[Here is a video showing the desired behavior.](https://drive.google.com/file/d/1c0raB6BwV5J7jWUZ9tJ34ltllkbGswIn/view?usp=sharing)

**Comment by ionutiorgulescu** [comment]
Firefox behavior close all popups when extension is losing focus, it's an opened issue still not resolved, https://bugzilla.mozilla.org/show_bug.cgi?id=1366330 there are two workarounds:

1. to open the extension as a browser page like this: moz-extension://"ID"/index.html
   - ID can be found here about:debugging#/runtime/this-firefox and it's the Internal UUID from Filecoin Retreival extension
2. to disable the autohide, but this will make the extension always opened.
   - this can be done from about:config then search for ui.popup.disable_autohide and make it true

Edit: I've add a new icon near PeersIndicator, if clicked will open the extension as a webpage. (PR: #33 )

Demo: https://drive.google.com/file/d/1uc_Wkvpee-dFwxMIxxkSY4SgyBYi9Mk0/view?usp=sharing
