### ISSUE TITLE
Websocket connection to retrieve a file using a Retrieval Proxy

### ISSUE THREAD

**Issue by brunolm** [agencyenterprise/filecoin-retrieval-browser-extension#42]
Related: https://github.com/mgoelzer/proxy-retrieval/issues/27

![image](https://user-images.githubusercontent.com/706078/95230331-216c2d00-07d8-11eb-863f-52b720db321e.png)

Browser:

1. request a CID
    - if NOT available: gets `available: false` and stops
1. sends a message indicating that funds have been sent
    - insufficient funds: stops
    - price changed: stops
1. QueryRetrievalStatus
1. Chunk
1. ChunkReceived
1. ChunkResend

## QueryCid / CidAvailability

- [x] send
  - [x] send CID from query form
  - [x] send miner from query form
```
{
  message
  cid
  miner
}
```

- [x] handle
  - [x] if available
    - [x] continue connection
    - [x] send funds (#97)
    - [x] send `FundsSent` message
  - [x] if NOT available
    - [x] end connection
    - [x] display some feedback message
  - [x] save client token for future messages
```
{
  available
  cid
  client_token
  message
  payment_wallet
  price_attofil
}
```

## FundsSent / FundsConfirmed

- [x] send
```
{
  message
  client_token
  payment_wallet
}
```

- [ ] handle
  - [ ] `funds_confirmed`: continue
  - [ ] `funds_confirmed_error_insufficient_funds`: x
  - [ ] `funds_confirmed_error_price_changed`: x
```
{
  message
  cid
  payment_wallet
  remaining_balance
}
```

## QueryRetrievalStatus

- [ ] send
  - [ ] every N seconds check status ???
```
{
  message
  cid
  client_token
}
```
- [ ] handle
  - [ ] display ???
```
{
  message
  cid
  status
}
```

## Chunk

- [ ] send with `clientToken`
  - [x] on success `ChunkReceived`
  - [x] on error `ChunkResend` N times
    - [ ] define and set N
    - invalid sha256
    - invalid length
    - any error
```
{
  message
  client_token
  cid
  id
}
```

- [ ] handle
  - [x] validate `sha256`
  - [x] validate `length`
```
{
  chunk_data
  chunk_len_bytes
  chunk_sha256
  cid
  full_data_len_bytes
  full_data_sha256
  id
  message
}
```

**Comment by ghost** [comment]
Closing because @brunolm moved to "Done" pipeline.
