### ISSUE TITLE
Rendezvous IP rejects some hostnames but not others

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#47]
On Options, Rendezvous IP works correctly with `jsrc-bootstrap.goelzer.io` but not with `webrtc-star-1.browser-retrieval.filecoin.io`.  The latter stays stuck at "Trying to connect to rendezvous server" and no peers are ever found.  **Both resolve to the same IP address.**

We need to fix `webrtc-star-1.browser-retrieval.filecoin.io` so it can work.

**Comment by mgoelzer** [comment]
Couldn't reproduce

**Comment by ghost** [comment]
Closing in favor of #63
