### ISSUE TITLE
Create a notification system to show users when errors happen

### ISSUE THREAD

**Issue by brunolm** [agencyenterprise/filecoin-retrieval-browser-extension#64]
# What

- [ ] when an error occurs show an "error" div with the message and a button to dismiss

# Why

Users can only see error if they go to the logs tab, it's not clear if things are working on not unless they analyze logs

# Additional Details
 - Here's a sketch of roughly how I envision this looking
<img width="746" alt="Screen Shot 2020-10-18 at 9 22 46 PM" src="https://user-images.githubusercontent.com/225111/96398023-12965a80-1188-11eb-82d0-6dcea18bba4f.png">

 - Note that there can be 0 or 1 or 2 or more error bars being displayed at the same time.  They persist until "Dismiss" is pressed.

 - We need to be able to post these errors from background.  Thus, my suggestion is to modify `ports.js` so that we can make a call like this from anywhere:

```
ports.addErrorBar("Error:  There is a chicken on the roof.");
```

**Comment by ghost** [comment]
@brunolm I updated the description a bit with some details I thought of over the weekend
