### ISSUE TITLE
Figure out why Lotus endpoint works as a numeric IP but not a hostname

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#74]
Setting Lotus IP to `http://3.231.219.184:80/rpc/v0` works fine, but `http://cloud-lotus-1.browser-retrieval.filecoin.io:80/rpc/v0` does not.

These are the same server.  It is running a Caddy proxy that reroutes `:80` to internal `:1234`.  There is no SSL on the server, so that can't be the problem.  Maybe `/etc/caddy/Caddyfile` needs to be told about hostnames?

Another approach is to test with [curl requests](https://docs.filecoin.io/reference/lotus-api/#curl-examples) and see what the response is when using `http://3.231.219.184:80/rpc/v0` versus `http://cloud-lotus-1.browser-retrieval.filecoin.io:80/rpc/v0`. curl will show the headers being sent back too.

**Comment by ghost** [comment]
@aistoc @ionutiorgulescu @brunolm Your ssh public keys are already on this machine if you want to look at the Caddyfile or caddy logs.

**Comment by ghost** [comment]
Additional info:  this is the error that Chrome produces when the hostname `cloud-lotus-1.browser-retrieval.filecoin.io` is used:

```
Access to XMLHttpRequest at 'http://cloud-lotus-1.browser-retrieval.filecoin.io/rpc/v0' from origin 'chrome-extension://genbehkplgecempflfleakfbaiobpdgi' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

So maybe `http://cloud-lotus-1.browser-retrieval.filecoin.io/rpc/v0` triggers a redirect to the numeric IP and that's what it's objecting to.  curl headers would prove this.

**Comment by ionutiorgulescu** [comment]
I've fixed it.

- changed in /etc/caddy/Caddyfile `:80` with `cloud-lotus-1.browser-retrieval.filecoin.io`
- then I run `sudo service caddy restart`
