### ISSUE TITLE
getOptions constants are overridden by whatever is in local storage

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#89]
If we make a code change to the getOptions.js `const defaultValues` section, compile and then refresh the extension, the change will be ignored.  The problem is this function:

```
function getOptions() {
  return new Promise(resolve => {
    chrome.storage.local.get(optionsKeys, result => {
      resolve({ ...defaultValues, ...result });
    });
  });
}
```

To reproduce:
 - Change some `const defaultValues` value in `getOptions.js`.  For example, change the `lotusToken` to `zzz`.
 - yarn rebuild
 - Refresh extension in 2 browsers
 - Not that the code still works even though `lotusToken` is wrong.

You can see the result in the Log tab here:

```
DEBUG: Lotus.getNonce:
  addr=f173kt4jpp344ly4ne6zc2wljmzdj7sdls6nrwuxi
  this.headers={ Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR*********************************************************************************************************************' }
  this.lotusEndpoint=http://3.231.219.184:80/rpc/v0
```

Expected behavior:  The Bearer field above should say `zzz`.  Thus, this should break the extension (payment channels functions, specifically).  The problem is that the old `lotusToken` value in chrome storage is still being used.

Fix:
 - When getOptions() is called, read back each *hardcoded* value in `const defaultOptions` and compare it to the value in chrome storage.
 - If they differ, override chrome storage with the `const defaultOptions` value.

**Comment by brunolm** [comment]
I think this would be equivalent

```js
resolve({ ...result, ...defaultValues });
```

This may however break things because there are settings we expect to come from the storage and the default is just an initial placeholder value.

Maybe the best thing here would be to split `defaultValues` into two, having one of the parts be `hardcodedValues` and the other `initialValues`, and then maybe have:

```js
resolve({ ...initialValues, ...result, ...hardcodedValues });
```

**Comment by brunolm** [comment]
https://github.com/filecoin-shipyard/browser-retrieval/commit/ab80d5ebdb50e726d0e4ee70a29c2d9ea4da9a46
