### ISSUE TITLE
Replace "Invalid Key Length" multiple errors with instructions

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#93]
**The Problem**  Right now, if you uninstall and do a clean install of the browser extension, you will notice that you get 3 separate "Invalid key length" errors.  This isn't a very good experience for new users.

**Solution** When the extension UI first loads, it should check whether or not the `Wallet` and `Private key (secp256k1)` fields are empty.  If one (or both) of these fields is empty, it should pop up a _modal, overlay_ box that prompts the user like this:

```
Before you can start using this tool, you must supply a wallet address and base64 private key.

Wallet (secp256k1):   ________________________________
Private key:  _____________________________________

                             [ Continue ]
```

**Other**

 - [x] The user cannot do anything with the rest of the UI until these two fields are filled in and validate correctly.

 - [x] I'd like to also show light grey example text inside the two input fields that disappears when the user clicks inside.  For wallet, it should show:  `f156e3l2vwd5wi5jwdrd6gdg4y7t2yknq6see7xbq`.  For private key field:  `ciiFbmF7F7mrVs5E/IT8TV63PdFPLrRs9R/Cc3vri2I=`.

**Comment by ionutiorgulescu** [comment]
<img width="1673" alt="Screenshot 2020-10-27 at 16 06 03" src="https://user-images.githubusercontent.com/5168735/97312674-6848c200-186e-11eb-83cb-c6503caf22ef.png">

What do you think?

**Comment by ghost** [comment]
@ionutiorgulescu I think it's good.  I haven't had time to build this version yet and test, but from the screenshot, yes, this is what I was thinking.  Could you maybe create a short video demoing it, show it to me, and we can merge based on that?

**Comment by ionutiorgulescu** [comment]
https://docs.google.com/presentation/d/1TurNjWV_3AZwgeHK9GhqFy_HaSp1uvZQvabxnU-zn5c
