### ISSUE TITLE
Query CID fixes

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#94]
- [ ] Remove the * next to Query CID
- [ ] Add a line (smaller font) between Query CID and the input box that says `Enter a CID to search the network for (try QmVmEHjr6xtNxHDbJ7kXenYMH6C4ZGpjqNnMeAEk9dQcR3)`
- [ ] Make sure the user can highlight, copy and paste the `QmVm....` part into the input box

<img width="438" alt="Screen Shot 2020-10-26 at 8 42 17 PM" src="https://user-images.githubusercontent.com/225111/97250532-ca9cb680-17cb-11eb-9713-9f2ebf56a63e.png">

(Ignore the red underline in the image.)

**Comment by ionutiorgulescu** [comment]
<img width="1678" alt="Screenshot 2020-10-27 at 13 52 02" src="https://user-images.githubusercontent.com/5168735/97298527-34fd3780-185c-11eb-9b81-3397403b2efb.png">
