### ISSUE TITLE
Get Caddy working and document all commands

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#95]
@ionutiorgulescu @aistoc Here's a machine running lotus on `127.0.0.1:1243`:  `ssh -i <your key> ubuntu@18.206.194.223`

See if you and your devops people can figure out how to get caddy installed and reverse proxying  `18.206.194.223:443 -> 127.0.0.1:443`.

You can test with curl like this:  

From the command prompt on 18.206.194.223 (works already):
```
curl -X POST  -H "Content-Type: application/json"  -H "Authorization: Bearer $(cat ~/.lotus/token)"  --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 1 }'  'http://127.0.0.1:1234/rpc/v0'
```

From your local laptop:
```
curl -X POST  -H "Content-Type: application/json"  -H "Authorization: Bearer $(cat ~/.lotus/token)"  --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 1 }'  'http://18.206.194.223:443/rpc/v0'
```

There is no AWS firewall on the machine (all IP4 ports are open).  The machine itself is running a ufw firewall like this:

```
ubuntu@lotus-caddy-test:~$ sudo ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22                         ALLOW IN    Anywhere
[ 2] 443                        ALLOW IN    Anywhere
[ 3] 5555                       ALLOW IN    Anywhere
[ 4] 22 (v6)                    ALLOW IN    Anywhere (v6)
[ 5] 443 (v6)                   ALLOW IN    Anywhere (v6)
[ 6] 5555 (v6)                  ALLOW IN    Anywhere (v6)
```

So, 443 is open to the outside world.  Need to install caddy first, get it listening on 443, then reverse proxy that to 127.0.0.1:1234 and the second curl command (from your laptop) should work.

**DOCUMENT EVERY COMMAND YOU RUN.  That way, we can reproduce this on the other Lotus machines later.**

**Comment by ionutiorgulescu** [comment]
Resolved this in the proxy-retrieval repo.
