### ISSUE TITLE
Create a Lotus function to send funds to a wallet

### ISSUE THREAD

**Issue by brunolm** [agencyenterprise/filecoin-retrieval-browser-extension#97]
## What

A function to send funds to a wallet.

Probably in `src/background/lotus-client/Lotus.js`

### Resources
- Related issue #42 
- [Document with all the specs](https://docs.google.com/document/d/1swBHR9xaFVH5l26wgIRw6pqUlQbYBWeLDLgka-SmC8k/edit#)

## Why

Because with the proxy the client needs to transfer the funds before sending a `FundsSent` message

---

##### FundsSent

```
{
  "message":"funds_confirmed",
  "client_token":"HIgP2JW9wHdlTYb89rjEy9/IQDR02EwMvtg4XN5Y/kY=",
  "payment_wallet":"f1stoztiw5sxeyvezjttq5727wfdkooweskpue5fa",
}
```

This is a message the browser sends to the RP to indicate funds have been sent.  RP will watch that wallet address until funds are received (+6 more blocks for confirmation).

#####  FundsConfirmed

```
{
  "message":"funds_confirmed",
  "cid":"bafk2bzacebbhqzi4y546h7gjbduauzha6z33ltequ7hpbvywnttc57xrwcit2",
  "payment_wallet":"f1stoztiw5sxeyvezjttq5727wfdkooweskpue5fa",
}
```

This message is sent from the RP to the Browser when the RP discovers that the payment to its wallet address has been confirmed on chain (initial confirmation + 6 blocks).

**Comment by ghost** [comment]
@aistoc @brunolm Here is some implementation advice.  Happy to jump on Zoom and talk through this with you if it's not clear.

There are two parts to sending funds to a wallet:

1. On the browser side, we need to submit a send message to the chain.
2. On the lotus side, we need to wait for those funds to appear in the receiving wallet.

## Sending Funds (Browser Side)

For this we need to generate and sign a message.  It must be _from_ the browser's wallet (and _signed by_ the browser's private key).  It must be _to_ the recipient wallet address.

To generate the send message itself, I would recommend following this example code in [filecoin-signing-tools/examples/wasm_browser/index.js#L69-L89](https://github.com/mgoelzer/filecoin-signing-tools/blob/master/examples/wasm_browser/index.js#L69-L89).

Then you will need to mPoolPush the message onto the chain using the cloud lotus.  There is a function to do mPoolPush() already in [Lotus.js#L92-118](https://github.com/filecoin-shipyard/browser-retrieval/blob/master/src/background/lotus-client/Lotus.js#L92-L118).  I recommend using that function and putting your higher level "SendFunds()" function (whatever function calls mPoolPush) in Lotus.js also so it has access to mPoolPush() and the globals mPoolPush() relies on (e.g., `headers`).  

There is a complete example of doing an mPoolPush with a pre-signed message in [Lotus.js#L277-L310](https://github.com/filecoin-shipyard/browser-retrieval/blob/b86cf7eaa66c6dd24d16d5c3a1f46064c80d27cc/src/background/lotus-client/Lotus.js#L277-L310).  Notice that:
 - you need to wait for the response to your message so you can catch the error (if there is one).  For now we just write errors to the log, but in the future we'll add real error handling.
 - before you can call mPoolPush you need to get a nonce for the From wallet and sign the message containing the nonce.  [Lotus.js#L277-L310](https://github.com/filecoin-shipyard/browser-retrieval/blob/b86cf7eaa66c6dd24d16d5c3a1f46064c80d27cc/src/background/lotus-client/Lotus.js#L277-L310) shows the full sequence of steps you need to do.
 - please print to the Log the msgCid return value of mPoolPush so we can debug why messages fail when they do.

## Checking for Receipt of Funds (Proxy Server Side)

On the server side, you just want to poll the wallet every 15 seconds or so to see when it has received funds.  Here's an example of how you could do this (except you want to call `Filecoin.WalletBalance` not `Filecoin.WalletList`:  [filecoin-signing-tools/examples/wasm_node/payment_channel.js#L253-L259](https://github.com/Zondax/filecoin-signing-tools/blob/ccefd77dedcae1bab894e7fc111f2ffda8fb1dfe/examples/wasm_node/payment_channel.js#L253-L259)

Another option would be to shell out to the Lotus CLI.  You can check the balance of any wallet like this:

```
$ lotus wallet balance f173kt4jpp344ly4ne6zc2wljmzdj7sdls6nrwuxi
0.937445247128109196 FIL
```

The CLI version is probably easier to implement.  Either way, make sure to have some unit tests that cover known failure cases.  For example, here's the CLI trying to check the balance of an invalid wallet:

```
$ lotus wallet balance f1000000000000000000000000000000000000000
ERROR: illegal base32 data at input byte 0
```

and here's the CLI trying to check the balance of a valid but empty wallet:

```
$ lotus wallet balance f156e3l2vwd5wi5jwdrd6gdg4y7t2yknq6see7xbq
0 FIL (warning: may display 0 if chain sync in progress)
```
